### ISSUE TITLE
Device listing and specific control

### ISSUE THREAD

**Issue by ThatTonybo** [SharkFinPro/razer-chroma-nodejs#1]
Any methods built in or planned to list all devices and control them specifically? Also, what's backwards compatibility like?

**Comment by SharkFinPro** [comment]
This is my first time making something with documentation, so it is not the best, sorry about that haha.
I always use the LTS version of node.js and have not tested others so i do not know backwards compatability in that respect as of now.

For controlling devices specifically, do you mean a specific device as in you have two mice and you want to set each to a different color, or a different device as in a mouse and a headset for example.

**Comment by SharkFinPro** [comment]
@ThatTonybo I have updated the documentation so now it should be a bit more clear on how to interect with different sets of devices.

**Comment by ThatTonybo** [comment]
@SharkFinPro Sorry didn't say it right, I meant backwards compatibility with older chroma devices. I personally own devices that need synapse 3, and a keyboard (deathstalker chroma) that needs synapse 2. Just looking to try make a program that can control them all in one program.

As for specific devices, I mean different as in two different devices, ie. keyboard and headset.

Don't worry about your documentation though, nobody's really that good with it.

**Comment by SharkFinPro** [comment]
My headset (razer tiamat 7.1 v2) uses syntapse 2, all my other devices use syntapse 3...and all of them work perfectly fine using this api. So what version of syntapse should not affect anything.

**Comment by SharkFinPro** [comment]
If you have any further input or questions please open another issue as this one appears to be answered :)
