### ISSUE TITLE
wave , .cycleSpectrum() not working 

### ISSUE THREAD

**Issue by ArtichautDev** [SharkFinPro/razer-chroma-nodejs#5]
Hi , how to use .cycleSpectrum() and .wave effect please
its not working for me 
my code : 
 const Chroma = require("razer-chroma-nodejs");

        // Initialize Chroma
        Chroma.util.init(() => {
            console.log("Chroma Editing Started");

            // Set the mouse color to green
            Chroma.effects.all.cycleSpectrum()
                // Close Chroma after 5 seconds
            setTimeout(() => {
                Chroma.util.uninit(() => {
                    console.log("Chroma Editing Stopped");
                });
            }, 5000);
        });

error : 
Chroma Editing Started
Error: connect ECONNREFUSED 127.0.0.1:58547
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58547
}
Error: connect ECONNREFUSED 127.0.0.1:58547
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58547
}
Error: connect ECONNREFUSED 127.0.0.1:58547
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58547
}
Error: connect ECONNREFUSED 127.0.0.1:58547
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58547
}
Error: connect ECONNREFUSED 127.0.0.1:58547
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58547
}
Error: connect ECONNREFUSED 127.0.0.1:58547
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58547
}
Chroma Editing Stopped

thanks for reading this

**Comment by SharkFinPro** [comment]
I just went through and fixed a bunch of things.
This issue should now be fixed, if it is not please let me know!

Check the readme as some things have changed :)

**Comment by ArtichautDev** [comment]
My code:
Chroma.util.init(() => {
    console.log("Chroma Editing Started");

    // Set the mouse color to green
    Chroma.effects.all.wave(1);
    // Close Chroma after 5 seconds

});
Error :
Chroma.effects.all.wave(1);
                       ^

TypeError: Chroma.effects.all.wave is not a function
    at Timeout._onTimeout (C:\Users\pierr\Documents\Chroma\razer.js:11:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by ArtichautDev** [comment]
But wave is on razer synapse ....

**Comment by ArtichautDev** [comment]
i use wave on razer synapse for all my device

**Comment by ArtichautDev** [comment]
cycleSpectrum is working now :D

**Comment by SharkFinPro** [comment]
Please check the readme for all documented effects.

The wave effect has only been recreated here for the mousepad so far, I will implement it for more devices if I have time.

If there are any other effects that you want to see, please let me know!

**Comment by ArtichautDev** [comment]
but why wave for all devices do not exist ?

**Comment by SharkFinPro** [comment]
It has not been developed. This is not using the same code as for Razer Synapse, this is using the rest API
