### ISSUE TITLE
wave not working

### ISSUE THREAD

**Issue by ArtichautDev** [SharkFinPro/razer-chroma-nodejs#6]
My code:
Chroma.util.init(() => {
console.log("Chroma Editing Started");

// Set the mouse color to green
Chroma.effects.all.wave(1);
// Close Chroma after 5 seconds
});
Error :
Chroma.effects.all.wave(1);
^

TypeError: Chroma.effects.all.wave is not a function
at Timeout._onTimeout (C:\Users\pierr\Documents\Chroma\razer.js:11:24)
at listOnTimeout (node:internal/timers:557:17)
at processTimers (node:internal/timers:500:7)

**Comment by ArtichautDev** [comment]
sorry for double post 
D:
![image](https://user-images.githubusercontent.com/91349238/147887064-7f0e0fb3-6355-4159-a903-3b129675bb8e.png)

**Comment by SharkFinPro** [comment]
The wave effect has yet to be added for more devices than the mousepad. I will add more when I have time.

**Comment by ArtichautDev** [comment]
ok thanks

**Comment by ArtichautDev** [comment]
i use your module for create a module for sync every razer device with every light strip and connected led with razer :D

**Comment by SharkFinPro** [comment]
Cool!

**Comment by ArtichautDev** [comment]
Can you add me on discord ? Artichaut#5655 ? because i really need wave i pay for it 🤣

**Comment by SharkFinPro** [comment]
okay

**Comment by SharkFinPro** [comment]
wave for mousepad smoothed out, and a wave has been added for the keyboard. Other devices may come later.
